#!/bin/sh
#
#	cart_svg --
#		Generate the start of a SVG element that uses Cartesian
#		coordinates (origin at lower left, x increases rightward,
#		y increases upward).
#
# Usage:
#	carg_svg x0 y0 w h w_px
# where:
#	x0	- real world x coordinate of plot origin
#	y0	- real world y coordinate of plot origin
#	w	- width of plot in real world units
#	h	- height of plot in real world units
#	w_px	- width of the plot on output device, pixels.
#
# Optional environment variables:
#	SVG_ATT	- additional attributes for svg element, e.g. id="myplot"
#	LEFT	- x coordinate of svg element. Defaults to 0.
#	TOP	- y coordinate of svg element. Defaults to 0.
#
# SVG code goes to standard output.
# Output should be terminated with "</g></svg>" to complete the element.

if [ $# -ne 5 ]
then
    echo "Usage: $0 x0 y0 width height width_px" 2>&1
    exit 1
fi
x0=$1
y0=$2
w=$3
h=$4
w_px=$5
LEFT=${LEFT:-"0"}
TOP=${TOP:-"0"}
h_px=`echo "$w_px / $w * $h" | bc -l`
printf '
<svg
    x="%.1f"
    y="%.1f"
    width="%.1f"
    height="%.1f"
    viewBox="%.1f %.1f %.1f %.1f"
    %s
>
<g
    transform="matrix(1 0 0 -1 0 %.1f)"
>
' $LEFT $TOP $w_px $h_px $x0 $y0 $w $h "$SVG_ATT" $h
exit
